### ISSUE TITLE
support docker as a "runtime"

### ISSUE THREAD

**Issue by aszs** [onecommons/unfurl#10]
Instead of running unfurl in a python virtual machine we should have an option to have it run inside of docker.
The runtime specifier could be "docker:image" (instead "venv:"), "docker:" alone would use a default container image we supply.

Here's some pseudocode for invoking a container with docker so that it has access to the local file system and the local docker daemon:

    root_dir = project_root
    reldir = os.path.relpath('.', root_dir)
    exec docker run -it --rm \
        -u $(id -u):$(id -g) \
        -e HOME="/home/$USER" -e USER=$USER -v "$HOME":"/home/$USER" \
       -v "$root_dir":/data \
        -w /data/$reldir \ # workdir is cwd in container
        -v /var/run/docker.sock:/var/run/docker.sock
        $CONTAINER_NAME $unfurl_cmd

Of course the container would have to be trusted when used in this manner. The entry point for adding this  support is [`_remoteCmd` in `__main__`](https://github.com/onecommons/unfurl/blob/master/unfurl/__main__.py#L217

**Comment by jozo** [comment]
Proposed command line arguments:

- `--privileged` - runs docker container in priviliged mode
- `--docker-args '-v "/a/b:/c/d"'` - adds additional arguments to docker runtime

**Comment by aszs** [comment]
> Proposed command line arguments:
> 
> * `--privileged` - runs docker container in priviliged mode
> * `--docker-args '-v "/a/b:/c/d"'` - adds additional arguments to docker runtime

These need to be runtime in the runtime specifier that can appear both on the command line and in the `unfurl.yaml` so having separate command line args instead of being part of the runtime specifier seems confusing

**Comment by aszs** [comment]
@jozo see https://unfurl.run/docs/projects.html#runtime for the syntax for the `venv:` runtime

**Comment by aszs** [comment]
fixed!
