### ISSUE TITLE
Better colors in log output

### ISSUE THREAD

**Issue by aszs** [onecommons/unfurl#120]
Current colors as it looks in one terminal 

<img width="786" alt="Screen Shot 2022-04-15 at 1 19 21 PM" src="https://user-images.githubusercontent.com/626790/163629474-eed232fb-a35b-4521-bfca-a86a0ad3ed01.png">

and another:

<img width="768" alt="Screen Shot 2022-04-15 at 1 24 41 PM" src="https://user-images.githubusercontent.com/626790/163629473-2155a880-7360-45c0-8a4d-bc00c2474f17.png">

Available colors: https://click.palletsprojects.com/en/8.0.x/api/#click.style

**Comment by AjBreidenbach** [comment]
@christinezapata the terminal user can usually change the value for each color and the background, as well as the background opacity (one of the screenshots has some transparency)

this might be a useful resource for checking various colors https://terminal.sexy/
there's a scheme browser tab you can check what different themes look like
some common ones are darkula and solarized (probably a few more)

**Comment by aszs** [comment]
i tweaked the colors when logging, think it is good enough for now... turns out its really hard to detect whether a terminal is in light or dark mode... there are some common envvars but they are unreliable (e.g. iterm sets COLORFGBG but it lies) and there's a escape sequence but not every terminal supports it, see https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color
