### ISSUE TITLE
Terraform not in PATH after installation by asdf

### ISSUE THREAD

**Issue by meru1a** [onecommons/unfurl#123]
After first run of unfurl plan/deploy terraform gets installed by asdf but then executable not found by unfurl CLI

**Comment by aszs** [comment]
This should be partially fixed in 7493292d by updating the artifact implementation to call `asdf local`. But only partially because the `.tool-versions` is only read when unfurl starts.

**Comment by aszs** [comment]
this should be fixed in 886fd805
