### ISSUE TITLE
Jinja search paths are not set correctly when target template not at/below yaml caller 

### ISSUE THREAD

**Issue by detjensrobert** [onecommons/unfurl#239]
Trying to render a Jinja template from Unfurl YAML does not work when the template being rendered is not at-or-below the yaml file rendering the template.

<table>
<tr>
  <td> Works </td>
  <td> Does NOT work </td>
</tr>
<tr>
  <td>
  
  ```sh
  # both in root
  unfurl-types/caller.yaml
  unfurl-types/templates/foo.j2
 
  # both in subdir
  unfurl-types/subdir/caller.yaml
  unfurl-types/subdir/templates/foo.j2

  # template in subdir
  unfurl-types/caller.yaml
  unfurl-types/subdir/templates/foo.j2
  ```

  </td>
  <td>

  ```sh
  # caller in subdir
  unfurl-types/subdir/caller.yaml
  unfurl-types/templates/foo.j2
  ```

  </td>
</tr>
</table>

---

This is reproducible when planning or deploying any deployment using `ContainerComputeHost` or `HttpsProxyContainerComputeHost` using the types commit below.

The failing yaml in types is
```yaml
default:
  eval:
    template:
      path: "{{ 'docker-compute-host/templates/cloud-config.yaml.j2' | abspath('types') }}"
```
(See structure at this commit: https://gitlab.com/onecommons/unfurl-types/-/tree/700eb82ce919736ac685ae0626b75e232e9cd50f, `/generic/generic-types.yaml#L627`)

This sets the filename correctly, but the jinja search directories are still relative to that file, and not impacted by `abspath()`

```
unfurl cwd: /.../staging-dashboard-two/environments/test/onecommons/blueprints/nextcloud/nxc-types-test
unfurl template path: /.../staging-dashboard-two/unfurl-types/docker-compute-host/templates/cloud-config.yaml.j2
﻿
jinja looking in searchpaths: ['/.../staging-dashboard-two/unfurl-types/generic']
jinja trying open: /.../staging-dashboard-two/unfurl-types/generic/docker-compute-host/templates/docker-compose-template.yaml.j2
``` 
(common path prefix trimmed)

**Comment by aszs** [comment]
fixed in dd82106
