### ISSUE TITLE
Define Ansible Connection by Host Property

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#293]
When Unfurl creates the Ansible inventory, Unfurl will search at some point for the `public_ip` host attribute and use it, if defined, as `ansible_host`.
However, `ansible_connection` can not be set this way and is by default set to `local`.

Can we extend this logic to also specify `ansible_connection` by searching for a specific host property/ attribute?
Can we put `ansible_connection` to `ssh` by default if `ansible_host` has been defined by the `public_ip` host attribute?

If I am not wrong, I am talking about extending this case: https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/unfurl/configurators/ansible.py#L159

Best Greetings
Miles

**Comment by milesstoetzner** [comment]
I guess this request also applies for any property that one can set using `unfurl.capabilities.Endpoint.Ansible`.

**Comment by aszs** [comment]
You can set the `connection` property on the capability to set the ansible_connection.
And if you use `unfurl.capabilities.Endpoint.SSH` (which is derived from `unfurl.capabilities.Endpoint.Ansible`) that property defaults to `ssh` instead of `local`. I think this will fix this issue.

**Comment by milesstoetzner** [comment]
Yes, that is true. However, I hoped that I would not be required to model the capability but only rely on default properties in the node type definition.

**Comment by aszs** [comment]
Ah I see now -- Ok I just made this change in the testing branch: if ansible_connection is missing and we're setting ansible_host to the node's ip_address we'll also set ansible_connection to "ssh"
