### ISSUE TITLE
Running unit tests in tox should generate a code coverage report

### ISSUE THREAD

**Issue by aszs** [onecommons/unfurl#33]
When we run our unit tests with tox we should generate a code coverage report. `test-requirements.txt` current installs [coverage](https://coverage.readthedocs.io/en/coverage-5.5/) but it is used and I don't have any particular opinion about whether we should use that tool or some alternative.

**Comment by jozo** [comment]
Implemented in #40

**Comment by aszs** [comment]
fyi, example of a coverage script the fails when coverage isn't 100%: https://github.com/octodns/octodns/blob/master/script/coverage
