### ISSUE TITLE
Search in docs doesn't work

### ISSUE THREAD

**Issue by jozo** [onecommons/unfurl#55]
Go to [Unfurl docs](https://unfurl.run/docs/) and try search for something. It displays "Searching..." but no results shows up.

![Screenshot from 2021-05-24 13-54-57](https://user-images.githubusercontent.com/4247916/119344290-c3715480-bc97-11eb-916a-0d20de6ea71d.png)

One options is to fix search in sphinx. Another (more cool) option is to use https://docsearch.algolia.com

**Comment by aszs** [comment]
Looks like if we are building the docs with sphinx 3.4 or later, [search.html](https://github.com/myyasuda/sphinxbootstrap4theme/blob/master/themes/sphinxbootstrap4theme/search.html) needs to loads `_static/language_data.js`, see https://github.com/sphinx-doc/sphinx/issues/8591

**Comment by jozo** [comment]
I think we can close this - it will be fixed with new sphinx template.

**Comment by aszs** [comment]
closing, the new theme is live
