### ISSUE TITLE
Installation documentation needs clarifications

### ISSUE THREAD

**Issue by IoannisDritsas** [onecommons/unfurl#8]
## Initial Install Issues

[https://unfurl.run/docs/README.html#requirements](https://unfurl.run/docs/README.html#requirements)

This statement:

> If needed, Unfurl will download and install local copies of the following: Ansible, Terraform, gCloud, Supervisor, Helm, and asdf.

Needs clarification on __if needed__ part, on what the conditions are, with a link to details. Are these saved to `~/.unfurl_home` per project?

By default unfurl installs:

- Ansible as dependency

### Cryptography requires Cargo/Rust

[https://github.com/pyca/cryptography/blob/master/docs/installation.rst](https://github.com/pyca/cryptography/blob/master/docs/installation.rst)

```Bash
python --version
Python 3.6.9


pip --version
pip 18.1 from /home/dritsas/.pyenv/versions/3.6.9/envs/unfurl/lib/python3.6/site-packages/pip (python 3.6)
```

Resolution known to work:

- Use `export CRYPTOGRAPHY_DONT_BUILD_RUST=1`
- Upgrade pip version `pip install --upgrade pip`

Recommended addition to docs, when __rust compiler is missing__

```Bash
# Building cryptography from source, pip <= 20
export CRYPTOGRAPHY_DONT_BUILD_RUST=1
pip install unfurl

# Or Upgrade pip
pip install --upgrade pip
pip install unfurl
```

**Comment by aszs** [comment]
This is an issue with Python versions earlier than 3.7. I added pip >= 20 to requirements.txt and "officially" restored support for 3.6 in tox, travis and the readme. I also removed the sentence in the readme about local versions of software it installs. The answer to your question is that this happens when you run "unfurl deploy" on the "home" project created in .unfurl_home but mentioning that in that section of the readme is confusing.

**Comment by aszs** [comment]
Reopening, travis' 3.6 is still failing with this problem. But tox installs successfully on my mac with Python 3.6.13 (travis is using Ubuntu Xenial), need to investigate further.

**Comment by aszs** [comment]
Punting on fully restoring 3.6 support, updated the readme with this note:

Python 3.6 is not tested automatically but should work. However you should make sure you have the latest version of pip installed (`pip install -U pip`) and may need to have Rust installed for the [crytography library](https://github.com/pyca/cryptography/blob/main/docs/installation.rst).
