### ISSUE TITLE
Resource Card Save/Delete errors when going Back or refreshing

### ISSUE THREAD

**Issue by christinezapata** [onecommons/unfurl#92]
I was testing the Template Config page and had selected Azure, added a MongoDB, and then clicked the Back button and started a new deployment with GCP. 

The MongoDB resource card was erroneously saved and pre-filled with the green status indicator after I created a new deployment with the different cloud provider. 

When I added a new resource (Send Grid mail server), and then clicked refresh, the wrong resource card was saved. MongoDB resource card remained, but no card for SendGrid (but the status indicator was still green for both MongoDB and Mail Server). 

I tried again to connect to a resource - CloudDNS, but no new resource card appeared when I did this, and again saved the MongoDB card. Refreshing does not fix this issue.

**Comment by aszs** [comment]
closing.. added to the wrong project...
